name: Branch を Push したらイメージをビルドする

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Dockerfile 
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Build a image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ex3:dev
          #platforms: linux/amd64,linux/arm64
          labels: ex3:dev

      - name: Check vulnerabilities 
        run: |
          docker images
          docker run -v /var/run/docker.sock:/var/run/docker.sock --rm aquasec/trivy image --no-progress ex3:dev

      - name: Start a container from the image
        run: |
          docker images
          docker run -d --name test -p 9300:3000 ex3:dev
          docker ps -a

      - name: Test the container
        run: |
          sleep 5
          curl --silent --retry 3 --include  http://127.0.0.1:9300/ping | grep "200 OK" 
          [ $? -ne 0 ] && (echo "error"; exit 1)
          exit 0

